# Eureka - disabled
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# JWT production
spring.security.oauth2.resource-server.jwt.issuer-uri=https://sso.isums.pro/realms/isums

# Log
logging.level.org.springframework.security=WARN
logging.level.org.springframework.cloud.gateway=WARN

# USER DOCS
spring.cloud.gateway.server.webmvc.routes[0].id=users-docs
spring.cloud.gateway.server.webmvc.routes[0].uri=http://user-service:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/users/v3/api-docs,/api/users/v3/api-docs/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/api/users/v3/api-docs(?<segment>/?.*),/v3/api-docs${segment}
spring.cloud.gateway.server.webmvc.routes[0].filters[1]=AddRequestHeader=X-Forwarded-Prefix,/api/users
spring.cloud.gateway.server.webmvc.routes[0].filters[2]=AddRequestHeader=X-Forwarded-Proto,https

# USER API
spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://user-service:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/users,/api/users/**

# ECONTRACT DOCS
spring.cloud.gateway.server.webmvc.routes[2].id=econtract-docs
spring.cloud.gateway.server.webmvc.routes[2].uri=http://econtract-service:8082
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/econtracts/v3/api-docs,/api/econtracts/v3/api-docs/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=RewritePath=/api/econtracts/v3/api-docs(?<segment>/?.*),/v3/api-docs${segment}
spring.cloud.gateway.server.webmvc.routes[2].filters[1]=AddRequestHeader=X-Forwarded-Prefix,/api/econtracts
spring.cloud.gateway.server.webmvc.routes[2].filters[2]=AddRequestHeader=X-Forwarded-Proto,https

# ECONTRACT API
spring.cloud.gateway.server.webmvc.routes[3].id=econtract-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://econtract-service:8082
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/econtracts,/api/econtracts/**

# HOUSE DOCS
spring.cloud.gateway.server.webmvc.routes[4].id=house-docs
spring.cloud.gateway.server.webmvc.routes[4].uri=http://house-service:8083
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/houses/v3/api-docs,/api/houses/v3/api-docs/**
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=RewritePath=/api/houses/v3/api-docs(?<segment>/?.*),/v3/api-docs${segment}
spring.cloud.gateway.server.webmvc.routes[4].filters[1]=AddRequestHeader=X-Forwarded-Prefix,/api/houses
spring.cloud.gateway.server.webmvc.routes[4].filters[2]=AddRequestHeader=X-Forwarded-Proto,https

# HOUSE API
spring.cloud.gateway.server.webmvc.routes[5].id=house-service
spring.cloud.gateway.server.webmvc.routes[5].uri=http://house-service:8083
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/houses,/api/houses/**

# ASSET DOCS
spring.cloud.gateway.server.webmvc.routes[6].id=asset-docs
spring.cloud.gateway.server.webmvc.routes[6].uri=http://asset-service:8084
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/assets/v3/api-docs,/api/assets/v3/api-docs/**
spring.cloud.gateway.server.webmvc.routes[6].filters[0]=RewritePath=/api/assets/v3/api-docs(?<segment>/?.*),/v3/api-docs${segment}
spring.cloud.gateway.server.webmvc.routes[6].filters[1]=AddRequestHeader=X-Forwarded-Prefix,/api/assets
spring.cloud.gateway.server.webmvc.routes[6].filters[2]=AddRequestHeader=X-Forwarded-Proto,https

# ASSET API
spring.cloud.gateway.server.webmvc.routes[7].id=asset-service
spring.cloud.gateway.server.webmvc.routes[7].uri=http://asset-service:8084
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/assets,/api/assets/**

# AI API
spring.cloud.gateway.server.webmvc.routes[8].id=ai-service
spring.cloud.gateway.server.webmvc.routes[8].uri=http://ai-service:8090
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/ai,/api/ai/**
spring.cloud.gateway.server.webmvc.routes[8].filters[0]=StripPrefix=1

# SCHEDULE DOCS
spring.cloud.gateway.server.webmvc.routes[9].id=schedule-docs
spring.cloud.gateway.server.webmvc.routes[9].uri=http://schedule-service:8087
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/api/schedules/v3/api-docs,/api/schedules/v3/api-docs/**
spring.cloud.gateway.server.webmvc.routes[9].filters[0]=RewritePath=/api/schedules/v3/api-docs(?<segment>/?.*),/v3/api-docs${segment}
spring.cloud.gateway.server.webmvc.routes[9].filters[1]=AddRequestHeader=X-Forwarded-Prefix,/api/schedules
spring.cloud.gateway.server.webmvc.routes[9].filters[2]=AddRequestHeader=X-Forwarded-Proto,https

# SCHEDULE API
spring.cloud.gateway.server.webmvc.routes[10].id=schedule-service
spring.cloud.gateway.server.webmvc.routes[10].uri=http://schedule-service:8087
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/api/schedules,/api/schedules/**

# MAINTENANCE DOCS
spring.cloud.gateway.server.webmvc.routes[11].id=maintenance-docs
spring.cloud.gateway.server.webmvc.routes[11].uri=http://maintenance-service:8086
spring.cloud.gateway.server.webmvc.routes[11].predicates[0]=Path=/api/maintenances/v3/api-docs,/api/maintenances/v3/api-docs/**
spring.cloud.gateway.server.webmvc.routes[11].filters[0]=RewritePath=/api/maintenances/v3/api-docs(?<segment>/?.*),/v3/api-docs${segment}
spring.cloud.gateway.server.webmvc.routes[11].filters[1]=AddRequestHeader=X-Forwarded-Prefix,/api/maintenances
spring.cloud.gateway.server.webmvc.routes[11].filters[2]=AddRequestHeader=X-Forwarded-Proto,https

# MAINTENANCE API
spring.cloud.gateway.server.webmvc.routes[12].id=maintenance-service
spring.cloud.gateway.server.webmvc.routes[12].uri=http://maintenance-service:8086
spring.cloud.gateway.server.webmvc.routes[12].predicates[0]=Path=/api/maintenances,/api/maintenances/**

# ISSUE DOCS
spring.cloud.gateway.server.webmvc.routes[13].id=issue-docs
spring.cloud.gateway.server.webmvc.routes[13].uri=http://issue-service:8089
spring.cloud.gateway.server.webmvc.routes[13].predicates[0]=Path=/api/issues/v3/api-docs,/api/issues/v3/api-docs/**
spring.cloud.gateway.server.webmvc.routes[13].filters[0]=RewritePath=/api/issues/v3/api-docs(?<segment>/?.*),/v3/api-docs${segment}
spring.cloud.gateway.server.webmvc.routes[13].filters[1]=AddRequestHeader=X-Forwarded-Prefix,/api/issues
spring.cloud.gateway.server.webmvc.routes[13].filters[2]=AddRequestHeader=X-Forwarded-Proto,https

# ISSUE API
spring.cloud.gateway.server.webmvc.routes[14].id=issue-service
spring.cloud.gateway.server.webmvc.routes[14].uri=http://issue-service:8089
spring.cloud.gateway.server.webmvc.routes[14].predicates[0]=Path=/api/issues,/api/issues/**